name: Bug Report
description: Report a bug in CodeShamer
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      placeholder: "e.g., 1.95.0"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: CodeShamer Version
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 15.2, Windows 11, Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open a file with...
        2. Run the command...
        3. See the error...
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet (if applicable)
      description: The code that triggers the issue
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Extension Host Logs (if applicable)
      description: "Open Command Palette > Developer: Show Extension Host Log"
      render: text
