name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make CodeShamer better? We'd love to hear it!

  - type: dropdown
    id: type
    attributes:
      label: Type of feature
      options:
        - New detection rule
        - New language support
        - UI improvement
        - Configuration option
        - Quick fix / code action
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see? Why would it be useful?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Code examples or mockups showing how it would work
      render: text

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute this?
      options:
        - label: I'm willing to submit a PR for this feature
