import { ShamePattern } from "../types";

export const htmlRules: ShamePattern[] = [
	{
		id: "html-inline-style",
		pattern: /\bstyle=["'][^"']*["']/,
		severity: 3,
		category: "style",
		messageKey: "shame.html.inlineStyle",
		hintKey: "hint.html.inlineStyle",
	},
	{
		id: "html-marquee",
		pattern: /<marquee\b/i,
		severity: 4,
		category: "style",
		messageKey: "shame.html.marquee",
		hintKey: "hint.html.marquee",
	},
	{
		id: "html-br-tags",
		pattern: /<br\s*\/?>\s*<br\s*\/?>/i,
		severity: 2,
		category: "style",
		messageKey: "shame.html.brUsage",
		hintKey: "hint.html.brUsage",
	},
	{
		id: "html-center-tag",
		pattern: /<center\b/i,
		severity: 3,
		category: "style",
		messageKey: "shame.html.centerTag",
		hintKey: "hint.html.centerTag",
	},
	{
		id: "html-img-no-alt",
		pattern: /<img\b(?![^>]*\balt\s*=)[^>]*>/i,
		severity: 3,
		category: "reliability",
		messageKey: "shame.html.imgNoAlt",
		hintKey: "hint.html.imgNoAlt",
	},
	{
		id: "html-input-no-type",
		pattern: /<input\b(?![^>]*\btype\s*=)[^>/]*>/i,
		severity: 3,
		category: "reliability",
		messageKey: "shame.html.inputNoType",
		hintKey: "hint.html.inputNoType",
	},
	{
		id: "html-inline-onclick",
		pattern: /\bonclick\s*=/i,
		severity: 3,
		category: "style",
		messageKey: "shame.html.inlineOnclick",
		hintKey: "hint.html.inlineOnclick",
	},
	{
		id: "html-missing-lang",
		pattern: /<html\b(?![^>]*\blang\s*=)/i,
		severity: 2,
		category: "reliability",
		messageKey: "shame.html.missingLang",
		hintKey: "hint.html.missingLang",
	},
	{
		id: "html-empty-href",
		pattern: /<a\b[^>]*href\s*=\s*["']#["']/i,
		severity: 2,
		category: "reliability",
		messageKey: "shame.html.emptyHref",
		hintKey: "hint.html.emptyHref",
	},
	{
		id: "html-table-layout",
		pattern: /<table\b[^>]*\b(width|height)\s*=/i,
		severity: 2,
		category: "style",
		messageKey: "shame.html.tableLayout",
		hintKey: "hint.html.tableLayout",
	},
];
