import { ShamePattern } from "../types";

const isReactContext = (ctx: { languageId: string; filePath: string }) =>
	ctx.languageId.includes("react") ||
	/\.(jsx|tsx)$/.test(ctx.filePath);

export const javascriptRules: ShamePattern[] = [
	{
		id: "js-console-log",
		pattern: /console\.(log|debug|info|trace|table)\s*\(/,
		severity: 1,
		confidence: 0.98,
		engine: "ast",
		category: "debug",
		messageKey: "shame.js.consoleLog",
		hintKey: "hint.js.consoleLog",
	},
	{
		id: "js-var-usage",
		pattern: /\bvar\s+\w/,
		severity: 2,
		confidence: 0.95,
		engine: "ast",
		category: "style",
		messageKey: "shame.js.varUsage",
		hintKey: "hint.js.varUsage",
	},
	{
		id: "js-loose-equality",
		pattern: /[^!=]==[^=]/,
		severity: 2,
		confidence: 0.92,
		engine: "ast",
		category: "reliability",
		messageKey: "shame.js.looseEquality",
		hintKey: "hint.js.looseEquality",
	},
	{
		id: "js-loose-inequality",
		pattern: /!=[^=]/,
		severity: 2,
		confidence: 0.92,
		engine: "ast",
		category: "reliability",
		messageKey: "shame.js.looseInequality",
		hintKey: "hint.js.looseInequality",
	},
	{
		id: "js-eval",
		pattern: /\beval\s*\(/,
		severity: 5,
		confidence: 0.99,
		engine: "ast",
		category: "security",
		messageKey: "shame.js.eval",
		hintKey: "hint.js.eval",
	},
	{
		id: "js-debugger",
		pattern: /\bdebugger\b/,
		severity: 4,
		confidence: 1,
		engine: "ast",
		category: "debug",
		messageKey: "shame.js.debugger",
		hintKey: "hint.js.debugger",
	},
	{
		id: "js-empty-catch",
		pattern: /catch\s*\([^)]*\)\s*\{\s*\}/,
		severity: 3,
		category: "reliability",
		messageKey: "shame.js.emptyCatch",
		hintKey: "hint.js.emptyCatch",
	},
	{
		id: "js-alert",
		pattern: /\balert\s*\(/,
		severity: 2,
		confidence: 0.98,
		engine: "ast",
		category: "debug",
		messageKey: "shame.js.alert",
		hintKey: "hint.js.alert",
	},
	{
		id: "js-nested-ternary",
		pattern: /\?(?![.?])[^:]*\?(?![.?])/,
		severity: 2,
		category: "style",
		messageKey: "shame.js.nestedTernary",
		hintKey: "hint.js.nestedTernary",
	},
	{
		id: "js-new-function",
		pattern: /new\s+Function\s*\(/,
		severity: 5,
		category: "security",
		messageKey: "shame.js.newFunction",
		hintKey: "hint.js.newFunction",
	},
	{
		id: "js-document-write",
		pattern: /document\.write\s*\(/,
		severity: 4,
		category: "security",
		messageKey: "shame.js.documentWrite",
		hintKey: "hint.js.documentWrite",
	},
	{
		id: "js-settimeout-string",
		pattern: /setTimeout\s*\(\s*["'`]/,
		severity: 4,
		category: "security",
		messageKey: "shame.js.setTimeoutString",
		hintKey: "hint.js.setTimeoutString",
	},
	{
		id: "js-let-array-push",
		pattern: /let\s+\w+\s*=\s*\[\s*\];[\s\S]{0,150}?\.push\(/,
		severity: 3,
		category: "style",
		messageKey: "shame.js.letArrayPush",
		hintKey: "hint.js.letArrayPush",
		multiline: true,
	},
	{
		id: "js-switch-no-break",
		pattern: /case\s+[^:]+:(?:(?!break|return|throw)[^}])+case\s+/,
		severity: 5,
		category: "reliability",
		messageKey: "shame.js.switchNoBreak",
		hintKey: "hint.js.switchNoBreak",
		multiline: true,
	},
	{
		id: "js-react-key-index",
		pattern: /key\s*=\s*\{\s*(?:index|i)\s*\}/,
		severity: 3,
		category: "reliability",
		messageKey: "shame.js.reactKeyIndex",
		hintKey: "hint.js.reactKeyIndex",
		when: isReactContext,
	},
	{
		id: "js-react-dangerous-html",
		pattern: /dangerouslySetInnerHTML\s*=/,
		severity: 5,
		category: "security",
		messageKey: "shame.js.reactDangerousHtml",
		hintKey: "hint.js.reactDangerousHtml",
		when: isReactContext,
	},
	{
		id: "js-inner-html",
		pattern: /\.innerHTML\s*=/,
		severity: 4,
		category: "security",
		messageKey: "shame.js.innerHTML",
		hintKey: "hint.js.innerHTML",
	},
];
