import { ShamePattern } from "../types";

export const typescriptRules: ShamePattern[] = [
	{
		id: "ts-any-type",
		pattern: /:\s*any\b/,
		severity: 2,
		confidence: 0.98,
		engine: "ast",
		category: "reliability",
		messageKey: "shame.ts.anyType",
	},
	{
		id: "ts-as-any",
		pattern: /\bas\s+any\b/,
		severity: 3,
		confidence: 0.98,
		engine: "ast",
		category: "reliability",
		messageKey: "shame.ts.asAny",
	},
	{
		id: "ts-ignore",
		pattern: /@ts-ignore/,
		severity: 2,
		confidence: 1,
		category: "maintenance",
		messageKey: "shame.ts.tsIgnore",
	},
	{
		id: "ts-nocheck",
		pattern: /@ts-nocheck/,
		severity: 4,
		confidence: 1,
		category: "maintenance",
		messageKey: "shame.ts.tsNocheck",
	},
	{
		id: "ts-non-null-assertion",
		pattern: /\w+!\./,
		severity: 1,
		confidence: 0.95,
		engine: "ast",
		category: "reliability",
		messageKey: "shame.ts.nonNullAssertion",
	},
	{
		id: "ts-expect-error-no-reason",
		pattern: /@ts-expect-error$/,
		severity: 2,
		confidence: 0.9,
		category: "maintenance",
		messageKey: "shame.ts.expectErrorNoReason",
	},
];
